// const buffer = require("buffer");

export const encodedList = [
  "SGFwcHlFbWJhcnJhc3NlZEdpcmxz",
  "bm9ybWFsbnVkZXM=",
  "TnVkZV9TZWxmaWU=",
  "Rmxhc2hpbmdBbmRGbGF1bnRpbmc=",
  "UHVibGljRmxhc2hpbmc=",
  "QV9jdXBz",
  "ZG93bmJsb3VzZQ==",
  "U29sb19HaXJscw==",
  "UmVhbEppbGxpbmc=",
  "cHVmZmllcw==",
  "YnJhbGVzcw==",
  "cG9raWVz",
  "YWFfY3Vwcw==",
  "c21hbGxib29icw==",
  "QWxsTGFkaWVzU2hhdmVk",
  "T25seUZhbnMxMDFCcmFuZE5ldw==",
  "QmVuZHlHaXJscw==",
  "R3JvdXBPZk51ZGVHaXJscw==",
  "TW9vbmluZw==",
  "dGl0cw==",
  "TGFCZWF1dGVGZW1pbmluZQ==",
  "ZnJlY2tsZWRnaXJscw==",
  "Z2luZ2Vy",
  "SWNhbnNlZXlvdXJuaXBwbGVz",
  "ZmxhdHRpZXM=",
  "c2tpbm55dGFpbA==",
  "c21hbGx0aXRzY2xlYXZhZ2U=",
  "eHNtYWxsZ2lybHM=",
  "YWRvcmFibGVudWRlcw==",
  "dGlueXRpdHM=",
  "ZmxhdGNoZXN0cw==",
  "cGFsZWdpcmxz",
  "c21hbGxib29icw==",
  "QUk=",
  "UG9ybmRlcmZ1bEFJ",
  "QUludWRlcw==",
  "QW1hdGV1cm51ZGU=",
  "U2x1dHNvZm9ubHlmYW5z",
  "TnVkZXM=",
  "QWRvcmFibGVOdWRlcw==",
  "R29kUHVzc3k=",
  "b25seWZhbnNjaGlja3M=",
  "RXF1YWxseVRvcGxlc3M=",
  "Y2FzdWFsbnVkaXR5",
  "U2x1dA==",
  "RWxzYXM=",
  "b25seW51ZGVjaGlja3M=",
  "QW1hdGV1cg==",
  "UHVzc2llc0Nsb3NlVXA=",
  "Qm9vYmllcw==",
  "U2V4eUZyZXg=",
];

export function prettyPrintList() {
  // console.log(list.map(item => buffer.Buffer.from(item).toString('base64')));
  return encodedList.map((item) => atob(item));
}
